### PR TITLE
Support regular expressions in tests transaction name node

### PR DESCRIPTION
**Pull request by szmc**

### CODE REVIEW

**Comment by automatictester** [comment]
Hi, thanks for this PR. I can see you didn't merge master into your branch since you cloned the repo. This was in Nov last year. Can you please resolve conflicts?

**Comment by szmc** [comment]
Conflicts resolved, ready for merge/review.

**Comment by automatictester** [comment]
Here is my CSV file:

```
timeStamp,elapsed,label,responseCode,threadName,dataType,success,bytes,Latency
1434291247743,3514,Login,200,Thread Group 1-2,,true,444013,0
1434291247541,3780,Login,200,Thread Group 1-1,,true,444236,0
1434291247949,3474,Login,200,Thread Group 1-3,,true,444041,0
1434291248160,3448,Login to admin portal,200,Thread Group 1-4,,true,444712,0
1434291248359,3700,Login to regular website,200,Thread Group 1-5,,true,444054,0
```

Here is XML:

```
<?xml version="1.0" encoding="UTF-8"?>
<testSet>
    <passedTransactionsTest>
        <testName>Test #1</testName>
        <description>Verify number of passed tests</description>
        <transactionName>Login*</transactionName>
        <regexp></regexp>
        <allowedPercentOfFailedTransactions>0</allowedPercentOfFailedTransactions>
    </passedTransactionsTest>
</testSet>
```

And there is output:

```
Test name:            Test #1
Test type:            passedTransactionsTest
Test description:     Verify number of passed tests
Transaction name:     Login*
Expected result:      Percent of failed transactions <= 0
Actual result:        No transactions with label equal to 'Login*' found in CSV file
Transaction count:    0
Test result:          IGNORED
```

Test should process all 5 transactions, but didn't find even a single one. To me, the core part that is missing here is wildcard processing - so that `Login*` matches `Login`n `Login to corporate portal` etc.

**Comment by automatictester** [comment]
This cannot be merges in its current form. Closing.

**Pull request closed without merging**
