### PR TITLE
Changes to allow Teamcity to see Tests failed or Tests passed strings to mark a build red or green

### PR DESCRIPTION
**Pull request by ggeda**
Changes to allow Teamcity to see Tests failed or Tests passed strings to mark a build red or green.
I am new to do a pull request and contribute, please let me know if anything is missing.

### CODE REVIEW

**Comment by automatictester** [comment]
First of all, thanks for contributing! I'm glad to see you take care of unit tests too.

What I don't fully understand is what you want to achieve here. TeamCity will mark build as green or red depending on [exit code](https://github.com/automatictester/lightning/wiki/CI-Server-Integration). From what I can see you would like to include overall status not only in native TeamCity build status, but also in build description. Why? Is the build color not enough?

Two more things on technical side: this change should be applied to CIReporter, not TeamCityReporter - this would cause Jenkins and TeamCity to be inconsistent. Also, you should be checking failed+ ignored, not just failed - that would make the description inconsistent with the exit code (and build color subsequently).

**Comment by ggeda** [comment]
Thanks for the quick response and for a great tool. This is what I did and observed 
**1**. I have a concurrency teamcity build that runs jmeter script.I executed lightning after the test execution is completed.   
**2**. I used, -xml =  maxResponseFile so some jmeter tests fail (example Login page)  and some pass (example Home page load) based on the maxResponse threshold, all after a successful execution of the whole script( therefore no execution error and no exit -1 ). Therefore the default TeamCity behaviour is to go green. In this case, I have one test failed, one test passed. Using this report then, I want to mark the whole concurrency test build to go red because failed > 0. I changed the TeamCityReporter to say 'Test failed:' and in teamCity I added 'Additional Failure Conditions on specific text in build log' to look for **'Test failed:'**.
**3**. I am not checking ignored, because in unit test for example we do @Ignore purposely and we don't use that to fail the unit testing build. If a test is ignored, we ignore its result too.
**4**. I only changed the TeamCityReporter because, I don't know how Jenkins may need it and thought the safest thing is to leave it as is. Thanks

**Comment by automatictester** [comment]
We have a few points here. In Lightning, test is ignored, if an internal error occured and test couldn't execute successfully. Lightning tests are atomic, and failure of one test will not affect other tests. So in general if if Lightning test is marked as ignored, it means something went wrong. Difference between ignored and failed is: failed means e.g. we didn't have 0 failed transactions as we expected, while ignored means: we didn't manage to assess if we had 0 failed transactions or not, because something went wrong. This is not the same as @Ignore in unit testing.

No problem with TeamCityReporter, I can change CIReporter if we make a decision to process this code change.

I think we still slightly misunderstand each other in case of the core issue you describe. Let me describe how I undrestand what you wrote. If I'm wrong please correct me.

You have 1 JMeter JMX file which produces 1 CSV result file. In this CSV file you have 2 transaction types which are relevant for you: Login page and Home page. You have 2 separate Lightning tests for them, one of them passes, another fails. If any of Lightning tests fails, Lightning will exit with non-zero exit code. If you call Lightning as the last step of your shell script which you execute from TeamCity, TeamCity will mark the build as failed automatically. There is no need to parse Lightning output to know that - exit code is enough. Just make sure call to Lightning is the last thing your script does.

If you think I misunderstood something and above explanation is not clear or correct, can you please post the following:
- lightning xml config file
- lightning output
- script which you use to execute Lightning
- screenshot of TeamCity build configuration
- actual result
- result that you expect instead of actual result

If you don't want to share those details with broad public, please send the files by email.
However, discussion about defect will continue here, not by email.

**Comment by ggeda** [comment]
I think we are on the same page. Lightning statements were not the very last , I had a finished log at the end. I fixed that and running TeamCity build , but takes a while for it to finish, will update here later.

This was what the log had , when TeamCity not color it Red
 INFO: lightning for TC> ============= EXECUTION SUMMARY =============
 INFO: lightning for TC> Tests executed:    16
 INFO: lightning for TC> Tests passed:      13
 INFO: lightning for TC> Tests failed:      3
 INFO: lightning for TC> Tests ignored:     0
 INFO: lightning for TC> Test set status:   FAIL
 INFO: lightning for TC> Execution time:    59ms
 INFO: lightning for TC>
 INFO: lightning for TC> Set TeamCity build status text:
 INFO: lightning for TC> ##teamcity[buildStatus text='Tests executed: 16, failed: 3, ignored: 0']
 INFO: finished; runtime = 0h, 2m, 22s, 625ms

**Comment by ggeda** [comment]
So, I made the change to make sure that lightning is the last thing the script does. And, TeamCity still show green. In the log below, You may see two lines after the lightning report, that my script has no control (looks like teamcity native lines). Could those two lines after the lightning report be the problem here? any suggestion to not see them ? Thanks,

[10:22:49][Wed Nov 04 10:22:49 EST 2015] INFO: lightningV2> ============= EXECUTION SUMMARY ============= 
[10:22:49][Wed Nov 04 10:22:49 EST 2015] INFO: lightningV2> Tests executed:    16 
[10:22:49][Wed Nov 04 10:22:49 EST 2015] INFO: lightningV2> Tests passed:      2 
[10:22:49][Wed Nov 04 10:22:49 EST 2015] INFO: lightningV2> Tests failed:      1 
[10:22:49][Wed Nov 04 10:22:49 EST 2015] INFO: lightningV2> Tests ignored:     13 
[10:22:49][Wed Nov 04 10:22:49 EST 2015] INFO: lightningV2> Test set status:   FAIL 
[10:22:49][Wed Nov 04 10:22:49 EST 2015] INFO: lightningV2> Execution time:    256ms 
[10:22:49][Wed Nov 04 10:22:49 EST 2015] INFO: lightningV2>  
[10:22:49][Wed Nov 04 10:22:49 EST 2015] INFO: lightningV2> Set TeamCity build status text: 
[10:22:49][Wed Nov 04 10:22:49 EST 2015] INFO: lightningV2> 
[10:22:49]##teamcity[buildStatus text='Tests executed: 16, failed: 1, ignored: 13']
[10:22:49] 
[10:22:49]Process exited with code 0

**Comment by ggeda** [comment]
As a follow up, I added a teamCity additional failure conditions, to look for 'Test set status:   FAIL' and fail it if found. So, with that, I can use lightning as is with no change. So, I will cancel my pull request. But, pursue my Q and A , to see make it work without a teamcity additional failure condition as @automatictester suggested above.

**Comment by ggeda** [comment]
By the way, I am using TeamCity 8

**Comment by automatictester** [comment]
Yeah, you can definitely use `Test set status: FAIL` to mark build as failed, no need for this MR to be processed. Although, I'd like to figure out what the problem with exit code is.

I can't reproduce this problem neither using Teamcity 9 nor 8 (TeamCity 8.1.5 build 30240 to be precise). When I have failed or ignored test, my exit code is non-zero and build fails:

    [18:59:35][Step 1/1] ============= EXECUTION SUMMARY =============
    [18:59:35][Step 1/1] Tests executed: 3
    [18:59:35][Step 1/1] Tests passed: 2
    [18:59:35][Step 1/1] Tests failed: 1
    [18:59:35][Step 1/1] Tests ignored: 0
    [18:59:35][Step 1/1] Test set status: FAIL
    [18:59:35][Step 1/1] Execution time: 255ms
    [18:59:35][Step 1/1]
    [18:59:35][Step 1/1] Set TeamCity build status text:
    [18:59:35][Step 1/1] ##teamcity[buildStatus text='Tests executed: 3, failed: 1, ignored: 0']
    [18:59:35][Step 1/1] Process exited with code 1
    [18:59:35][Step 1/1] Step Verify (Command Line) failed

If you want me to investigate it further, please make sure you use most recent Lightning version (1.0.0) and provide the following info:

- operating system TeamCity runs on
- Lightning output
- whole script you use to execute Lightning
- entire console output

My assumption is you may execute some command after lightning (let it be even `echo `), which causes Lightning's exit code to be overwritten.

**Comment by ggeda** [comment]
Thanks, I added the call to lightning jar from with in a groovy scipt that execute the jmeter test. At the end the very end I call lightning pointing to the CSV result file just created above. I am working some alternatives and get back to you with what I come out.

**Comment by ggeda** [comment]
Hi, After I closed the first pull request, I created a new pull request for a change on TeamCity 'build problem' messages. It resolved my problem of seeing failed build in red. It follows this teamcity doc ( https://confluence.jetbrains.com/display/TCD8/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-ReportingBuildProblems)

**Pull request closed without merging**
