### PR TITLE
fixes #35 - support for regexp in test transactioName node

### LINKED ISSUE #35: [lightning] Support regular expressions in tests' transactionName node
Given config file contains

```
<avgRespTimeTest>
    <testName>Test #1</testName>
    <description>Verify average login times</description>
    <transactionName>.*page access</transactionName>
    <maxAvgRespTime>4000</maxAvgRespTime>
</avgRespTimeTest>
```

When JMeter transactions are parsed
Then only transaction with name equal to **.*page access** included.

---

Given config file contains

```
<avgRespTimeTest>
    <testName>Test #1</testName>
    <description>Verify average login times</description>
    <transactionName>.*page access</transactionName>
    </regexp>
    <maxAvgRespTime>4000</maxAvgRespTime>
</avgRespTimeTest>
```

When JMeter transactions are parsed
Then all transaction with name matching **.*page access** regular expression are included.

---

Above change is backwards-compatible. New behavior is applied only if **&lt;/regexp&gt;** is present.

Some implementation tips:
- add check for **regexp** element to all private methods in **LightningXMLFileReader**
- create helper method for the above in **LightningXMLProcessingHelpers**
- add **protected boolean regexp** to **LightningTest**, defaulting to **false**
- we will need a method in **JMeterTransactions** to cover both scenarios - exact match and regexp; currently **excludeLabelsOtherThan** handles only exact match

I assume this can be handled on **LightningTest** level and can be transparent for all non-abstract test classes in the same package.

### PR DESCRIPTION
**Pull request by alex-fournier**

### CODE REVIEW

**Comment by automatictester** [comment]
Hi Alex, many thanks for your PR! There were some problems with CI config on your PR, which I now fixed. The good thing is that pipeline is green! I'll take a detailed look into your code shortly.

**Comment by alex-fournier** [comment]
Thank you, it will be useful for our tests automation.

**Comment by alex-fournier** [comment]
Is there a new release of lightning planned soon?

**Comment by automatictester** [comment]
If you need the new functionality I may try to release it today or tomorrow.

**Comment by alex-fournier** [comment]
Yes I need it, it would be very nice of you!

**Pull request merged**
