### PR TITLE
Junit report suffix

### PR DESCRIPTION
**Pull request by martymcflywa**
See #109 

This PR aims to add support for optional junit report suffix `ConfigurationMojo` property, to enable multiple executions with individual junit reports. If this property is not provided in the configuration, then the plugin should be behave as normal, with the junit filename as `junit.xml`

### CODE REVIEW

**Comment by automatictester** [comment]
Many thanks for opening this PR. I had a look at the code and it looks really good to me. One thing I don't like as much is passing null down the stack only to ignore it, although this is probably me being pedantic about clean code. Let's not spend our time thinking too much about that ;)
Could you create an item under [Resource List](http://automatictester.github.io/lightning/resources.html) describing this functionality for Maven plugin? If you could do that, I can get it merged and released to Maven Central quickly.

**Comment by martymcflywa** [comment]
I'm more than happy to make sure we stick to standards and clean code before getting the feature in. I've refactored how the suffix is set, and will have a commit to add documentation after work.

**Comment by automatictester** [comment]
Many thanks for your contribution, you can expect new version released to Maven Central shortly.

**Comment by martymcflywa** [comment]
Thanks for taking the time to review and responding so quickly!

**Pull request merged**
